[package]
name = "xeh"
version = "0.1.0"
authors = ["rivo <db05@bk.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
minifb = "0.16"

[dependencies]
#im-rc = "14.3"
rpds = "0.7"
#anyhow = "1"
#arccstr = "1.3"
num-bigint = "0.2.6"
num-traits = "0.2"
sha-1 = "0.8.2"

[profile.release]
opt-level = "s"
