[package]
name = "xeh"
version = "0.1.0"
authors = ["rivo <db05@bk.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = "14.3"
rpds = "0.7"
anyhow = "1"
num-bigint = "0.2.6"

[profile.release]
opt-level = "s"
