[package]
name = "xeh"
version = "0.1.0"
authors = ["rivo <db05@bk.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpds = "0.7"
rustyline = "6.1.2"
getopts = "0.2"
rand = "*"

[dev-dependencies]
minifb = "0.16"
font-kit = "0.5"
raqote = "0.7"

